Sr 478 csv download
micronutrientsupport/micronutrient-support-tool pull request #518
Opened 2021-06-07 14:52 UTC by Sveouu

CSV download now available for:

-  Monthly food Group
-  Top Food Source
-  Household Histogram
-  Projected Availability 
- Projected Food Source

Export service removes "_sourceObject" column.

CSV download button disabled when no data for chosen mn is available.

2021-06-07 15:14 UTC, Fuhji commented
Testing with Malawi

- [x] monthly food
- [x] top 20 food (had to use madagascar)
- [ ] household dietary supply - empty csv? Had to click 3 times to get download
- [x] projected availability
- [x] projection food sources

2021-06-07 15:17 UTC, Fuhji commented on src/app/pages/quickMaps/pages/baselineDetails/householdSupply/householdSupply.component.html
> +    <mat-tab label=" About {{title}}">
I know spaces are ignored usually, but was this vscode formatter adding this pre-space?

2021-06-07 15:18 UTC, Fuhji commented on src/app/pages/quickMaps/pages/biomarkers/biomarkerStatus/biomarkerStatus.component.ts
> +  // private initialiseMap(mapElement: HTMLElement): L.Map {
delete if not needed

2021-06-07 15:18 UTC, Fuhji commented on src/app/pages/quickMaps/pages/biomarkers/biomarkerStatus/biomarkerStatus.component.ts
> +  // private triggerFitBounds(tabIndex: number): void {
delete commented block if not needed

2021-06-07 15:21 UTC, Fuhji reviewed
looks good and all works for me except Household dietary supply. not getting any console errors when clicking, just an empty csv.

2021-06-07 15:53 UTC, Sveouu commented
> looks good and all works for me except Household dietary supply. not getting any console errors when clicking, just an empty csv.

Thank you.
Have removed comments and fixed Household Histogram csv download.

2021-06-08 07:24 UTC, Fuhji approved these changes

2021-06-08 07:24 UTC, jon571 requested changes
I have a few concerns and a few suggestions :-)

Maybe we could have a screen share to talk through them?

2021-06-08 12:15 UTC, jon571 approved these changes

2021-06-08 12:41 UTC, merged